console.log(Math.PI);
console.log(Math.abs(-7));
console.log(Math.abs(7));
console.log(Math.floor(4.9));
console.log(Math.floor(4.9));
console.log(Math.ceil(4.1)); 
console.log(Math.ceil(4.1)); 
console.log(Math.round(4.4)); 
console.log(Math.round(4.5));
console.log(Math.trunc(4.9)); 
console.log(Math.trunc(4.9));
console.log(Math.random());
console.log(Math.min(5, 3, 9, 1));
console.log(Math.max(5, 3, 9, 1));
console.log(Math.pow(2, 3));
console.log(Math.sign(3));
console.log(Math.sign(3));
console.log(Math.sign(0));
console.log(Math.sign('3'));
console.log(Math.sqrt(4));
console.log(Math.cbrt(8));